config:
  credentials: []
  project_repos:
    code-repo.d4science.org/MaDgIK/eosc-explore:
      branch: master
      repo: https://code-repo.d4science.org/MaDgIK/eosc-explore
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-teal-dogfish.sh
        container: qc.acc_thirsty-purple-snake
  QC.Doc:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-corn-dhole.sh
        container: qc.doc_freaky-yellow-sponge
      code-repo.d4science.org/MaDgIK/eosc-explore git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-carmine-squirrel.sh
        container: qc.doc_ready-chartreuse-cougar
      code-repo.d4science.org/MaDgIK/eosc-explore markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-turquoise-dingo.sh
        container: qc.doc_hazy-tangerine-abyssinian
  QC.Lic:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-corn-akbash.sh
        container: qc.lic_cozy-pear-chin
  QC.Sty:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-tomato-ibis.sh
        container: qc.sty_tasty-goldenrod-wasp
  QC.Ver:
    repos:
      code-repo.d4science.org/MaDgIK/eosc-explore get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-platinum-gecko.sh
        container: qc.ver_seedy-brown-gorilla
timeout: 5400
